"""product season

Revision ID: 3b4827f4b96f
Revises: 68fcbe979332
Create Date: 2026-08-05 23:01:29.171447
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b4827f4b96f'
down_revision: Union[str, None] = '68fcbe979332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='all'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'season')
    # ### end Alembic commands ###
