"""tenant event_type + labels

Revision ID: 68fcbe979332
Revises: 6e8451120a64
Create Date: 2026-08-05 22:44:03.167803
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68fcbe979332'
down_revision: Union[str, None] = '6e8451120a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='festival'))
    op.add_column('tenant', sa.Column('labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'labels')
    op.drop_column('tenant', 'event_type')
    # ### end Alembic commands ###
