"""tenant custom domain

Revision ID: e7dd751f35dd
Revises: 45f5c7a3dc88
Create Date: 2026-08-05 23:55:03.388995
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7dd751f35dd'
down_revision: Union[str, None] = '45f5c7a3dc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenant', sa.Column('custom_domain_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tenant', sa.Column('domain_verify_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('tenant', sa.Column('dns_verified_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tenant_custom_domain'), 'tenant', ['custom_domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_custom_domain'), table_name='tenant')
    op.drop_column('tenant', 'dns_verified_at')
    op.drop_column('tenant', 'domain_verify_token')
    op.drop_column('tenant', 'custom_domain_active')
    op.drop_column('tenant', 'custom_domain')
    # ### end Alembic commands ###
