import {
  Store,
  MapPin,
  CalendarDays,
  Users,
  UtensilsCrossed,
  ShoppingBasket,
  Hammer,
  Mountain,
  Music,
  Baby,
  Beer,
  Wine,
  Coffee,
  Tent,
  Bike,
  Waves,
  Fish,
  Sailboat,
  Ship,
  TreePine,
  Snowflake,
  Sun,
  Camera,
  Flame,
  Footprints,
  Bird,
  Landmark,
  Palette,
  Ticket,
  Star,
  Heart,
  Gift,
  Sparkles,
  Car,
  BedDouble,
  Wifi,
  Trophy,
  Compass,
  Map as MapIcon,
  Leaf,
  Grape,
  type LucideIcon,
  HelpCircle,
} from "lucide-react";

/** name → lucide component. Keys are the canonical (lucide) names. */
const ICONS: Record<string, LucideIcon> = {
  Store,
  MapPin,
  CalendarDays,
  Users,
  UtensilsCrossed,
  ShoppingBasket,
  Hammer,
  Mountain,
  Music,
  Baby,
  Beer,
  Wine,
  Coffee,
  Tent,
  Bike,
  Waves,
  Fish,
  Sailboat,
  Ship,
  TreePine,
  Snowflake,
  Sun,
  Camera,
  Flame,
  Footprints,
  Bird,
  Landmark,
  Palette,
  Ticket,
  Star,
  Heart,
  Gift,
  Sparkles,
  Car,
  BedDouble,
  Wifi,
  Trophy,
  Compass,
  Map: MapIcon,
  Leaf,
  Grape,
};

/**
 * Curated icon options for pickers — canonical value + a friendly Romanian
 * label. Kept in sync with ICONS above.
 */
export const ICON_OPTIONS: { value: string; label: string }[] = [
  { value: "Mountain", label: "Munte" },
  { value: "TreePine", label: "Pădure" },
  { value: "Waves", label: "Lac / apă" },
  { value: "Fish", label: "Pescuit" },
  { value: "Sailboat", label: "Barcă / caiac" },
  { value: "Ship", label: "Vapor" },
  { value: "Footprints", label: "Drumeție" },
  { value: "Bike", label: "Bicicletă / ATV" },
  { value: "Car", label: "Mașină / tururi" },
  { value: "Tent", label: "Camping" },
  { value: "BedDouble", label: "Cazare" },
  { value: "Snowflake", label: "Iarnă / schi" },
  { value: "Sun", label: "Vară / soare" },
  { value: "Beer", label: "Bere" },
  { value: "Wine", label: "Vin" },
  { value: "Grape", label: "Vie / podgorie" },
  { value: "Coffee", label: "Cafea" },
  { value: "UtensilsCrossed", label: "Restaurant / gastronomie" },
  { value: "Music", label: "Muzică / concerte" },
  { value: "Camera", label: "Foto" },
  { value: "Flame", label: "Foc de tabără" },
  { value: "Bird", label: "Natură / faună" },
  { value: "Leaf", label: "Natură / verde" },
  { value: "Landmark", label: "Obiectiv / cultură" },
  { value: "Palette", label: "Artă / ateliere" },
  { value: "Hammer", label: "Meșteșuguri" },
  { value: "ShoppingBasket", label: "Produse locale" },
  { value: "Store", label: "Magazin" },
  { value: "Ticket", label: "Bilete" },
  { value: "Trophy", label: "Competiții" },
  { value: "Users", label: "Comunitate" },
  { value: "Baby", label: "Copii / familie" },
  { value: "Heart", label: "Recomandat" },
  { value: "Star", label: "Stea" },
  { value: "Gift", label: "Cadouri" },
  { value: "Sparkles", label: "Experiențe" },
  { value: "Compass", label: "Aventură" },
  { value: "MapPin", label: "Locație" },
  { value: "Map", label: "Hartă" },
  { value: "Wifi", label: "Wi-Fi" },
  { value: "CalendarDays", label: "Program / calendar" },
];

/** Romanian / lowercase aliases → canonical name (so free text still works). */
const ALIASES: Record<string, string> = {
  bere: "Beer",
  vin: "Wine",
  vie: "Grape",
  podgorie: "Grape",
  cafea: "Coffee",
  munte: "Mountain",
  padure: "TreePine",
  pădure: "TreePine",
  lac: "Waves",
  apa: "Waves",
  apă: "Waves",
  pescuit: "Fish",
  peste: "Fish",
  pește: "Fish",
  barca: "Sailboat",
  barcă: "Sailboat",
  caiac: "Sailboat",
  vapor: "Ship",
  drumetie: "Footprints",
  drumeție: "Footprints",
  trekking: "Footprints",
  bicicleta: "Bike",
  bicicletă: "Bike",
  atv: "Bike",
  masina: "Car",
  mașină: "Car",
  tur: "Car",
  camping: "Tent",
  cort: "Tent",
  cazare: "BedDouble",
  iarna: "Snowflake",
  iarnă: "Snowflake",
  schi: "Snowflake",
  vara: "Sun",
  vară: "Sun",
  soare: "Sun",
  restaurant: "UtensilsCrossed",
  mancare: "UtensilsCrossed",
  mâncare: "UtensilsCrossed",
  gastronomie: "UtensilsCrossed",
  muzica: "Music",
  muzică: "Music",
  concert: "Music",
  foto: "Camera",
  poze: "Camera",
  foc: "Flame",
  natura: "Leaf",
  natură: "Leaf",
  pasari: "Bird",
  păsări: "Bird",
  cultura: "Landmark",
  cultură: "Landmark",
  muzeu: "Landmark",
  arta: "Palette",
  artă: "Palette",
  atelier: "Palette",
  mestesug: "Hammer",
  meșteșug: "Hammer",
  produse: "ShoppingBasket",
  magazin: "Store",
  bilete: "Ticket",
  competitie: "Trophy",
  competiție: "Trophy",
  comunitate: "Users",
  copii: "Baby",
  familie: "Baby",
  inima: "Heart",
  inimă: "Heart",
  stea: "Star",
  cadou: "Gift",
  experienta: "Sparkles",
  experiență: "Sparkles",
  aventura: "Compass",
  aventură: "Compass",
  locatie: "MapPin",
  locație: "MapPin",
  harta: "Map",
  hartă: "Map",
  program: "CalendarDays",
  calendar: "CalendarDays",
};

/** Resolve free-text/alias input to a canonical ICONS key ("" if none). */
function canonicalKey(name: string): string {
  if (!name) return "";
  const trimmed = name.trim();
  if (ICONS[trimmed]) return trimmed;
  const lower = trimmed.toLowerCase();
  if (ALIASES[lower] && ICONS[ALIASES[lower]]) return ALIASES[lower];
  // Case-insensitive match against canonical names (e.g. "beer" → Beer).
  return Object.keys(ICONS).find((k) => k.toLowerCase() === lower) ?? "";
}

export function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Cmp = ICONS[canonicalKey(name)] ?? HelpCircle;
  return <Cmp className={className} />;
}
